### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by haizrul** [mrtztg/scribd_dl#1]
C:\Users\Amrie>cd C:\Users\Amrie\Desktop\scribd_dl-master

C:\Users\Amrie\Desktop\scribd_dl-master>scribd_dl.py -u email -p passwd -i link.txt

====== WebDriver manager ======
Current google-chrome version is 90.0.4430
Get LATEST driver version for 90.0.4430
Driver [C:\Users\Amrie\.wdm\drivers\chromedriver\win32\90.0.4430.24\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:51424/devtools/browser/897d76a7-4cd4-439e-9651-330a3c77cdbb
[0502/001548.726:INFO:CONSOLE(43)] "i18next: languageChanged en-US", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0502/001548.727:INFO:CONSOLE(43)] "i18next: initialized [object Object]", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0502/001548.934:INFO:CONSOLE(3)] "Hotjar not launching due to suspicious userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.93 Safari/537.36", source: https://static.hotjar.com/c/hotjar-1620130.js?sv=6 (3)
[0502/001550.136:INFO:CONSOLE(1)] "google sign in error [object Object]", source: https://s-f.scribdassets.com/webpack/monolith/1.1cfd9153d70f17451bd1.js (1)
[0502/001553.994:INFO:CONSOLE(3)] "Hotjar not launching due to suspicious userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/90.0.4430.93 Safari/537.36", source: https://static.hotjar.com/c/hotjar-1620130.js?sv=6 (3)
[0502/001554.127:INFO:CONSOLE(43)] "i18next: languageChanged en-US", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0502/001554.127:INFO:CONSOLE(43)] "i18next: initialized [object Object]", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
Traceback (most recent call last):
  File "C:\Users\Amrie\Desktop\scribd_dl-master\scribd_dl.py", line 61, in <module>
    listen_btn_el = WebDriverWait(driver, 60).until(
  File "C:\Users\Amrie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

C:\Users\Amrie\Desktop\scribd_dl-master>

**Comment by haizrul** [comment]
Managed to downloaded 2 audiobooks before i got this error though.

**Comment by haizrul** [comment]
Maybe this can solve the issue: https://stackoverflow.com/questions/62475252/hotjar-suspicious-useragent-error-nothing-on-google-trying-to-run-a-python-scr/66193676#66193676

**Comment by mrtztg** [comment]
Thanks, @haizrul for using this tool.
I made some changes to the source code just now.
Please clone it with the help of ```git clone https://github.com/mrtztg/scribd_dl.git```.
Execute it and tell me the result.

**Comment by haizrul** [comment]
Hi @mrtztg , thanks for the update. I've tested it and its working fine now. Great work! :)
