### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by cr1zydog** [mrtztg/scribd_dl#10]
====== WebDriver manager ======
'reg' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\PythonProjects\scribd_dl-master\scribd_dl-master\scribd_dl.py", line 30, in <module>
    driver = Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\daisypc\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\chrome.py", line 25, in __init__
    self.driver = ChromeDriver(name=name,
  File "C:\Users\daisypc\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 57, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "C:\Users\daisypc\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\utils.py", line 155, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

**Comment by mrtztg** [comment]
Thanks for using my script.
Do these steps and give the feedback:

- download latest scribd_dl (>1.2.1)
- Download latest chromedriver from this addres: https://chromedriver.chromium.org/downloads
- extract its files into scribd_dl root folder.
- run script like before
