### ISSUE TITLE
Getting error when using the script

### ISSUE THREAD

**Issue by cox890** [mrtztg/scribd_dl#11]
Haven't used it for a while just tried it but getting this error

`[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 94.0.4606
[WDM] - Get LATEST driver version for 94.0.4606
[WDM] - Driver [C:\Users\fury\.wdm\drivers\chromedriver\win32\94.0.4606.61\chromedriver.exe] found in cache
C:\Users\fury\Documents\Scribd\scribd_dl.py:30: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome(ChromeDriverManager().install(), options=chrome_options)

DevTools listening on ws://127.0.0.1:49682/devtools/browser/42d62ef0-9e32-49cf-bd68-13ea939ea51c
opening website...
logging in...
C:\Users\fury\Documents\Scribd\scribd_dl.py:52: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('.sign_in .login_or_email.email input').send_keys(
[9452:8144:1018/060113.885:ERROR:chrome_browser_main_extra_parts_metrics.cc(228)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[9452:8144:1018/060113.885:ERROR:chrome_browser_main_extra_parts_metrics.cc(231)] crbug.com/1216328: Checking Bluetooth availability ended.
[9452:460:1018/060113.885:ERROR:device_event_log_impl.cc(214)] [06:01:13.884] Bluetooth: bluetooth_adapter_winrt.cc:1073 Getting Default Adapter failed.
[9452:8144:1018/060113.885:ERROR:chrome_browser_main_extra_parts_metrics.cc(234)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[9452:8144:1018/060113.906:ERROR:chrome_browser_main_extra_parts_metrics.cc(238)] crbug.com/1216328: Checking default browser status ended.
C:\Users\fury\Documents\Scribd\scribd_dl.py:55: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('.sign_in .wrapper__password_input input').send_keys(
C:\Users\fury\Documents\Scribd\scribd_dl.py:58: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector('.sign_in button[type=submit]').click()
Opening https://www.scribd.com/audiobook/471771161/Clash-of-Steel-A-A-Treasure-Island-Remix
C:\Users\fury\Documents\Scribd\scribd_dl.py:95: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  book_name = driver.find_element_by_css_selector('h1[data-e2e=desktop-content-title]').text
C:\Users\fury\Documents\Scribd\scribd_dl.py:109: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  _chapters_list_el = driver.find_elements_by_css_selector(
C:\Users\fury\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py:483: UserWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  warnings.warn("find_element_by_* commands are deprecated. Please use find_element() instead")
Traceback (most recent call last):
  File "C:\Users\fury\Documents\Scribd\scribd_dl.py", line 124, in <module>
    chapters_list_el[i].click()
  File "C:\Users\fury\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\fury\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 693, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\fury\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\fury\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="#" class="menu_link" role="menuitem">...</a> is not clickable at point (160, 280). Other element would receive the click: <div role="dialog" aria-live="polite" aria-modal="true" aria-label="Consent Manager by Osano" id="bba8c2ea-aa39-4e5f-9df8-883b2518ee2f" aria-describedby="bba8c2ea-aa39-4e5f-9df8-883b2518ee2f__label" class="osano-cm-window__dialog osano-cm-dialog osano-cm-dialog--position_bottom-left osano-cm-dialog--type_box">...</div>
  (Session info: chrome=94.0.4606.81)
Stacktrace:
Backtrace:
        Ordinal0 [0x004EBDE3+2473443]
        Ordinal0 [0x00486661+2057825]
        Ordinal0 [0x00392438+1057848]
        Ordinal0 [0x003C27B9+1255353]
        Ordinal0 [0x003C0AE0+1247968]
        Ordinal0 [0x003BE8AD+1239213]
        Ordinal0 [0x003BD701+1234689]
        Ordinal0 [0x003B3567+1193319]
        Ordinal0 [0x003D56E3+1332963]
        Ordinal0 [0x003B3386+1192838]
        Ordinal0 [0x003D57CA+1333194]
        Ordinal0 [0x003E4ABF+1395391]
        Ordinal0 [0x003D55AB+1332651]
        Ordinal0 [0x003B2104+1188100]
        Ordinal0 [0x003B2F59+1191769]
        GetHandleVerifier [0x00672266+1549718]
        GetHandleVerifier [0x0071D4A7+2250711]
        GetHandleVerifier [0x0057718B+521403]
        GetHandleVerifier [0x00576229+517465]
        Ordinal0 [0x0048B79D+2078621]
        Ordinal0 [0x0048FB58+2095960]
        Ordinal0 [0x0048FC92+2096274]
        Ordinal0 [0x00499541+2135361]
        BaseThreadInitThunk [0x76F3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77927A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77927A6E+238]`

**Comment by chimeforest** [comment]
I'm getting this error too.
When I first ran the script (earlier today) it was fine.

I run the script,
It opens up a browsers,
It tries to log me in,
I have to do a few captcha,
It logs in,
It goes to the audiobook's page,
It sits there a few minutes,
Then it closes the browser and spits out the error stuff.

I moved the script to a different folder, would that make a difference?
Also, I'm trying to download an audiobook which I recently downloaded today (which I deleted), would that make a difference?

**Comment by mrtztg** [comment]
@ink79 @chimeforest 
Glad I made a script that can be helpful to you.
I released a new version with some changes.
Please download and use it. Then give me feedback
https://github.com/mrtztg/scribd_dl/releases/tag/1.2.2

**Comment by ink79** [comment]
@mrtztg, thanks for the update; it's working on some books but on a few books its just stuck at some chapter and resume once I select the next chapter

**Comment by mrtztg** [comment]
@

> @mrtztg, thanks for the update; it's working on some books but on a few books its just stuck at some chapter and resume once I select the next chapter

Please provide links of books that you can't download.

**Comment by ink79** [comment]
had a problem with this book https://www.scribd.com/audiobook/471771161/Clash-of-Steel-A-A-Treasure-Island-Remix
https://www.scribd.com/audiobook/504348906/Powder-Days-Ski-Bums-Ski-Towns-and-the-Future-of-Chasing-Snow

**Comment by ink79** [comment]
> > @mrtztg, thanks for the update; it's working on some books but on a few books its just stuck at some chapter and resume once I select the next chapter
> 
> Please provide links of books that you can't download.

also this one https://www.scribd.com/audiobook/497426479/The-Sweetest-Oblivion
