### ISSUE TITLE
New issues running the script

### ISSUE THREAD

**Issue by purrell** [mrtztg/scribd_dl#16]
I really love the script, but lately I've had a problem using it. I cloned the Github again and re-checked that I had all the requirements installed just to make sure I'm not wasting your time. But I am getting the following problems now.

====== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [C:\Users\user\.wdm\drivers\chromedriver\win32\101.0.4951.41\chromedriver.exe] found in cache
C:\Users\user\scribd_dl\scribd_dl.py:30: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome(ChromeDriverManager().install(), options=chrome_options)

DevTools listening on ws://127.0.0.1:56510/devtools/browser/c2f54e6a-6503-48d4-a685-000efd45cdfe
[14064:19704:0510/141226.411:ERROR:device_event_log_impl.cc(214)] [14:12:26.412] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[14064:19704:0510/141226.417:ERROR:device_event_log_impl.cc(214)] [14:12:26.417] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[14064:19704:0510/141226.417:ERROR:device_event_log_impl.cc(214)] [14:12:26.418] Bluetooth: bluetooth_adapter_winrt.cc:1165 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedByUserWill not be able to change radio power.
Traceback (most recent call last):
  File "C:\Users\user\scribd_dl\scribd_dl.py", line 137, in <module>
    audio_file_el = WebDriverWait(driver, WAITING_TIMEOUT).until(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
        Ordinal0 [0x0025B8F3+2406643]
        Ordinal0 [0x001EAF31+1945393]
        Ordinal0 [0x000DC610+837136]
        Ordinal0 [0x000D0442+787522]
        Ordinal0 [0x000D0C78+789624]
        Ordinal0 [0x000D24B2+795826]
        Ordinal0 [0x000CBF09+769801]
        Ordinal0 [0x000DDAC0+842432]
        Ordinal0 [0x00133E62+1195618]
        Ordinal0 [0x00124096+1130646]
        Ordinal0 [0x000FE636+976438]
        Ordinal0 [0x000FF546+980294]
        GetHandleVerifier [0x004C9612+2498066]
        GetHandleVerifier [0x004BC920+2445600]
        GetHandleVerifier [0x002F4F2A+579370]
        GetHandleVerifier [0x002F3D36+574774]
        Ordinal0 [0x001F1C0B+1973259]
        Ordinal0 [0x001F6688+1992328]
        Ordinal0 [0x001F6775+1992565]
        Ordinal0 [0x001FF8D1+2029777]
        BaseThreadInitThunk [0x778EFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77DD7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77DD7A4E+238]
        (No symbol) [0x00000000]

**Comment by purrell** [comment]
Just to clarify the experience. It logs in to my account, but gets stuck on Chapter 1. It can't advance or save.
