### ISSUE TITLE
File ".\scribd_dl.py", line 114, in <module>

### ISSUE THREAD

**Issue by laomeinote** [mrtztg/scribd_dl#17]
When the page was opened after login with credentials, it finally prompt like below.

File ".\scribd_dl.py", line 114, in <module>
Traceback (most recent call last):
  File ".\scribd_dl.py", line 114, in <module>
    def get_chapters_list_el() -> list[WebElement]:
TypeError: 'type' object is not subscriptable

**Comment by laomeinote** [comment]
Below is the full information:

 python .\scribd_dl.py -u "wowmarcomei@gmail.com" -p "z*U0dMN12JUv" -i my_links_file.txt

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_102.0.5005 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
.\scribd_dl.py:34: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome("./chromedriver", options=chrome_options)
.\scribd_dl.py:36: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome("chromedriver.exe", options=chrome_options)

DevTools listening on ws://127.0.0.1:59004/devtools/browser/09d9a555-8268-4622-8e2f-151cf1c64477
[17220:9224:0529/211938.931:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211938.932:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211940.707:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211940.708:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[20764:21276:0529/211942.997:ERROR:device_event_log_impl.cc(214)] [21:19:42.998] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[20764:21276:0529/211942.997:ERROR:device_event_log_impl.cc(214)] [21:19:42.998] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[17220:9224:0529/211951.500:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.501:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.511:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.512:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.379:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.380:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.381:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.383:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211953.680:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211953.681:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.053:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.055:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.058:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.058:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.524:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.525:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.734:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.735:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
Traceback (most recent call last):
  File ".\scribd_dl.py", line 114, in <module>
    def get_chapters_list_el() -> list[WebElement]:
TypeError: 'type' object is not subscriptable

**Comment by laomeinote** [comment]
python .\scribd_dl.py -u "username" -p "password" -i my_links_file.txt

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_102.0.5005 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))
.\scribd_dl.py:34: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome("./chromedriver", options=chrome_options)
.\scribd_dl.py:36: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = Chrome("chromedriver.exe", options=chrome_options)

DevTools listening on ws://127.0.0.1:59004/devtools/browser/09d9a555-8268-4622-8e2f-151cf1c64477
[17220:9224:0529/211938.931:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211938.932:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211940.707:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211940.708:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[20764:21276:0529/211942.997:ERROR:device_event_log_impl.cc(214)] [21:19:42.998] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[20764:21276:0529/211942.997:ERROR:device_event_log_impl.cc(214)] [21:19:42.998] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)
[17220:9224:0529/211951.500:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.501:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.511:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211951.512:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.379:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.380:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.381:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211952.383:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211953.680:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211953.681:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.053:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.055:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.058:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211954.058:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.524:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.525:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.734:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
[17220:9224:0529/211955.735:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -107
Traceback (most recent call last):
  File ".\scribd_dl.py", line 114, in <module>
    def get_chapters_list_el() -> list[WebElement]:
TypeError: 'type' object is not subscriptable
