### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by robochud** [mrtztg/scribd_dl#2]
Hello

I use your software with my fresh installed linux mint.
python3 scribd_dl.py -u "myemail" -p "mypassword" -i my_links_file.txt
I get this error with your example list:

====== WebDriver manager ======
Current google-chrome version is 90.0.4430
Get LATEST driver version for 90.0.4430
Driver [/root/.wdm/drivers/chromedriver/linux64/90.0.4430.24/chromedriver] found in cache
Traceback (most recent call last):
  File "scribd_dl.py", line 29, in <module>
    driver = Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by mrtztg** [comment]
Thanks for using this tool.
Please answer these questions:
* do you run this tool with 'sudo'?
* which version of Linux mint do you use?
* Can you copy here content of 'my_links_file.txt' file?

**Comment by robochud** [comment]
Hi. Sorry it works now for me. 
I have a special character in my password. I changed my password on the scribd homepage.

Does your script return a return value when the download is finished or something went wrong?

**Comment by mrtztg** [comment]
Great.
The script won't print the 'Finish' message. Just printing chapters download message.
If the script ends without error, it means everything was successful.
