### ISSUE TITLE
i get this unknown issue 

### ISSUE THREAD

**Issue by mohamdshams22** [mrtztg/scribd_dl#3]
i get this error and i dont know to to fix it fi you can help with it please 
====== WebDriver manager ======
Current google-chrome version is 91.0.4472
Get LATEST driver version for 91.0.4472
Driver [C:\Users\mohamd shams\.wdm\drivers\chromedriver\win32\91.0.4472.19\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:57412/devtools/browser/64589ff5-ba46-4bc7-b630-15008686144a
[0607/220559.055:INFO:CONSOLE(43)] "i18next: languageChanged en-US", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0607/220559.055:INFO:CONSOLE(43)] "i18next: initialized [object Object]", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0607/220601.631:INFO:CONSOLE(1)] "google sign in error [object Object]", source: https://s-f.scribdassets.com/webpack/monolith/1.c3be6a11ca883904e47c.js (1)
[0607/220603.931:INFO:CONSOLE(43)] "i18next: languageChanged en-US", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
[0607/220603.931:INFO:CONSOLE(43)] "i18next: initialized [object Object]", source: https://s-f.scribdassets.com/webpack/vendors/react16/react16.63d55263784387ae046b.dll.js (43)
Traceback (most recent call last):
  File "C:\Users\mohamd shams\Downloads\scribd_dl-master\scribd_dl-master\scribd_dl.py", line 65, in <module>
    listen_btn_el = WebDriverWait(driver, WAITING_TIMEOUT).until(
  File "C:\Users\mohamd shams\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

C:\Users\mohamd shams\Downloads\scribd_dl-master\scribd_dl-master>

**Comment by mrtztg** [comment]
Thank you for using my script.
The problem resolved. please download the latest version (1.2) and test it again.
Give me feedback please.
