### ISSUE TITLE
Timeout on login issue/Is this still working?

### ISSUE THREAD

**Issue by celtichawk** [mrtztg/scribd_dl#5]
Came across this when looking for an audiobook downloader and it led to this repo.

So two questions...

1, is this still working or if not, is there a more up to date alternative that does work?

2. I'm unsure of the answer to #the first question, but I've run into it hanging on logging in with this: 
logging in...
Traceback (most recent call last):
  File "./scribd_dl.py", line 44, in <module>
    login_email_btn_el = WebDriverWait(driver, WAITING_TIMEOUT).until(
  File "/home/jace/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

Using Ubuntu 20.04.2 here

**Comment by nt153133** [comment]
A work around for this is to just login with email manually, if you remove or comment out lines 39-54 in scribd_dl.py and change the sleep at line 57 to like 120 or 180 that will give you 2-3 minutes to manually log into the site in the chromium window and do the captcha. You have to run it with --display i think for the window to show.  Not an ideal solution but definitely worth it

**Comment by mrtztg** [comment]
Thank you for using my script.
The problem resolved. please download the latest version (1.2) and test it again.
Give me feedback please.

**Comment by celtichawk** [comment]
Having tried it on the latest Chrome, it is stuck on the listening to.. page and seems to ignore the -p flag for a password. I'll try again with the verbose option and see what happens

**Comment by Yesirc** [comment]
Has anyone found the solution yet??? Still getting the time out error..
