### ISSUE TITLE
webdriver error

### ISSUE THREAD

**Issue by evafans** [mrtztg/scribd_dl#6]
Current google-chrome version is 92.0.4515
Get LATEST driver version for 92.0.4515
Driver [C:\Users\Administrator\.wdm\drivers\chromedriver\win32\92.0.4515.107\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:5764/devtools/browser/1ba6ffdc-198a-4486-a6f6-a5d8ed1d69b5
Traceback (most recent call last):
  File "C:\scribd_dl-master\scribd_dl.py", line 30, in <module>
    driver = Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

C:\scribd_dl-master>

**Comment by mrtztg** [comment]
Thank you for using my script.
The problem resolved. please download the latest version (1.2) and test it again.
Give me feedback please.
